/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/board.glb -o src/app/components/Models/Board.jsx -k -K -r public 
*/

import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import Configurator from '../UI/configuration/Configurator'

export function Board(props) {
  const { nodes, materials } = useGLTF('/models/board.glb')
  return (
    <group {...props} dispose={null}>
      <Html
        center
        transform
        position={[0, 0.745, 0.01]}
        scale={[0.4, 0.79, 0.01]}
        occlude="blending"
        distanceFactor={1} 
        as='div'
        className='configurator'>
        <Configurator />
      </Html>
      <group name="Root_Scene">
        <group name="RootNode">
          <group name="ParkInfoBoard" position={[0, 0.751, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={[36.326, 40, 40]}>
            <mesh name="ParkInfoBoard_1" geometry={nodes.ParkInfoBoard_1.geometry} material={materials.wood_shade1} />
            <mesh name="ParkInfoBoard_2" geometry={nodes.ParkInfoBoard_2.geometry} material={materials.board} />
            <mesh name="ParkInfoBoard_3" geometry={nodes.ParkInfoBoard_3.geometry} material={materials.wood_shade2} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/board.glb')
