/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Island.glb -o src/app/components/Island.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Island(props) {
  const { nodes, materials } = useGLTF('/models/Island.glb')
  return (
    <group castShadow receiveShadow {...props} dispose={null}>
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh'].geometry} material={materials.mat10} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_1'].geometry} material={materials.mat4} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_2'].geometry} material={materials.mat20} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_3'].geometry} material={materials.mat22} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_4'].geometry} material={materials.mat14} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_5'].geometry} material={materials.mat17} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_6'].geometry} material={materials.mat13} />
      <mesh castShadow receiveShadow geometry={nodes['model064-Mesh_7'].geometry} material={materials.mat9} />
    </group>
  )
}

useGLTF.preload('/models/Island.glb')
