/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -o src/app/components/Plant3.jsx -r public public/models/plant3.glb 
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { usePortalStore } from '../state-management/activePortal';
import { Tablet } from './Tablet';
import { motion } from "framer-motion-3d"
import { PLANT_SPRING, PLANT_VISIBILITY_VARIANTS } from '../AnimationConstants';
import PlantCard from '../UI/monitor/PlantCard';
import * as THREE from 'three';
import { useThree } from '@react-three/fiber';

export function Plant3(props) {
  const { nodes, materials } = useGLTF('/models/plant3.glb')
  const { activePortal, hoveredPortal } = usePortalStore();

  const boxHelperRef = useRef();
  const scene = useThree((state) => state.scene);

  useEffect(() => {
    if (boxHelperRef.current) {
      boxHelperRef.current.update();
    }
  }, [props]);

  return (
    <group {...props} dispose={null}>
      <PlantCard visibility={!activePortal && hoveredPortal === props.name ? 'visible' : 'hidden'} plantData={props.data} />
      <group name='tabletBox' ref={(group) => {
        if (group) {
          const helper = new THREE.BoxHelper(group, 0x00ff00); // Green bounding box
          helper.visible = false; // Makes the helper invisible
          boxHelperRef.current = helper;
          scene.add(helper);
        }
      }}>
        <Tablet plantData={props.data} {...props} visible={activePortal === props.name ? true : false} />
        <group position-z={-1} position-y={-1.67} rotation={[Math.PI / 2, 0, 0]} scale={0.02}>
          <motion.mesh geometry={nodes.Mesh002.geometry} variants={PLANT_VISIBILITY_VARIANTS} initial='visible' transition={PLANT_SPRING} animate={(activePortal === props.name || activePortal === null) ? 'visible' : 'hidden' } material={materials['eb_house_plant_01.002']} />
          <motion.mesh geometry={nodes.Mesh002_1.geometry} variants={PLANT_VISIBILITY_VARIANTS} initial='visible' transition={PLANT_SPRING} animate={(activePortal === props.name || activePortal === null) ? 'visible' : 'hidden' } material={materials['Material.004']} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant3.glb')
