/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant1.glb -o src/app/components/Plant1.jsx -r public 
*/

import React from 'react'
import { Html, useGLTF } from '@react-three/drei'
import { useActivePortalStore } from '../state-management/activePortal'
import Temperature from '../UI/Temperature'
import Humidity from '../UI/Humidity'
import Moisture from '../UI/Moisture'
import MoistureGraph from '../UI/MoistureGraph'

function Content() {
  return (
    <group rotation-z={-Math.PI / 12} position-x={-0.1}>
      <Html
        position={[-0.5, 0.4, -0.5]}
        rotation-x={-Math.PI/2}
        style={{ userSelect: "none" }}
        as="div"
        className="wrapper"
        castShadow
        receiveShadow
        center
        transform
        distanceFactor={0.5}
      >
        <Temperature />
      </Html>
      <Html
        position={[0.8, 0.2, -0.6]}
        rotation-x={-Math.PI/2}
        style={{ userSelect: "none" }}
        as="div"
        className="wrapper"
        castShadow
        receiveShadow
        center
        transform
        distanceFactor={0.5}
      >
        <Humidity />
      </Html>
      <Html
        position={[0.9, 0.4, -0.1]}
        rotation-x={-Math.PI/2}
        style={{ userSelect: "none" }}
        as="div"
        className="wrapper"
        castShadow
        receiveShadow
        center
        transform
        distanceFactor={0.5}
      >
        <Moisture />
      </Html>
      <Html
        position={[-0.5, 0.4, -0.1]}
        rotation-x={-Math.PI/2}
        style={{ userSelect: "none" }}
        as="div"
        className="wrapper"
        castShadow
        receiveShadow
        center
        transform
        distanceFactor={0.5}
      >
        <MoistureGraph />
      </Html>
    </group>
  );
}

export function Plant1(props) {
  const { nodes, materials } = useGLTF('/models/plant1.glb')
  const { activePortal } = useActivePortalStore();
  return (
    <group {...props} dispose={null}>
      <group position={[0, -113.445, 0]} rotation={[Math.PI / 2, 0, 0]} scale={227.159}>
        { activePortal === props.name && <Content />}
        <mesh geometry={nodes.awa_outdoor.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.awa_outdoor_1.geometry} material={materials['10461_Yucca_Plant_v1']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant1.glb')
