/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/Plants - Assorted shelf plants.glb -o src/app/components/Shelf.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Shelf(props) {
  const { nodes, materials } = useGLTF('/models/Plants - Assorted shelf plants.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.group929991637.geometry} material={materials.mat6} />
      <mesh geometry={nodes.mesh1308063879.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh1308063879_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh188964254.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh188964254_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh188964254_2.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh188964254_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh188964254_4.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1960316096.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1960316096_1.geometry} material={materials.mat8} />
      <mesh geometry={nodes.mesh1960316096_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1960316096_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1960316096_4.geometry} material={materials.mat0} />
      <mesh geometry={nodes.mesh1960316096_5.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh329520873.geometry} material={materials.mat18} />
      <mesh geometry={nodes.mesh329520873_1.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh329520873_2.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh681955559.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh681955559_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh37634377.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh37634377_1.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh24840230.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh24840230_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1292506990.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1292506990_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh760987982.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh760987982_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh507489342.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh507489342_1.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh307547309.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh307547309_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh307547309_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh307547309_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh343148839.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh343148839_1.geometry} material={materials.mat16} />
      <mesh geometry={nodes.mesh343148839_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh343148839_3.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh343148839_4.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh900961727.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh900961727_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh900961727_2.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh900961727_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh417557664.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh417557664_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh417557664_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh417557664_3.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh417557664_4.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1796822198.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1796822198_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1796822198_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh366088625.geometry} material={materials.mat3} />
      <mesh geometry={nodes.mesh366088625_1.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh735559431.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh735559431_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh735559431_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh735559431_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh492750791.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh492750791_1.geometry} material={materials.mat17} />
      <mesh geometry={nodes.mesh492750791_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh492750791_3.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1111774705.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1111774705_1.geometry} material={materials.mat5} />
      <mesh geometry={nodes.mesh1111774705_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1111774705_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1111774705_4.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1836607711.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh1836607711_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1836607711_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh1836607711_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1836607711_4.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh2025294802.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh2025294802_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh2025294802_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh2025294802_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh2025294802_4.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh1246536235.geometry} material={materials.mat0} />
      <mesh geometry={nodes.mesh1246536235_1.geometry} material={materials.mat12} />
      <mesh geometry={nodes.mesh1246536235_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh1246536235_3.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1246536235_4.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh839738285.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh839738285_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh839738285_2.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh839738285_3.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh633733193.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh633733193_1.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh633733193_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh633733193_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh190984041.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh190984041_1.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh190984041_2.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh190984041_3.geometry} material={materials.mat19} />
      <mesh geometry={nodes.mesh190984041_4.geometry} material={materials.mat15} />
      <mesh geometry={nodes.mesh211612252.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh211612252_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh211612252_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh211612252_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh689861939.geometry} material={materials.mat23} />
      <mesh geometry={nodes.mesh689861939_1.geometry} material={materials.mat13} />
      <mesh geometry={nodes.mesh1087234195.geometry} material={materials.mat22} />
      <mesh geometry={nodes.mesh1087234195_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh13645068.geometry} material={materials.mat14} />
      <mesh geometry={nodes.mesh13645068_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh13645068_2.geometry} material={materials.mat9} />
      <mesh geometry={nodes.mesh13645068_3.geometry} material={materials.mat10} />
      <mesh geometry={nodes.mesh718421555.geometry} material={materials.mat11} />
      <mesh geometry={nodes.mesh718421555_1.geometry} material={materials.mat20} />
      <mesh geometry={nodes.mesh718421555_2.geometry} material={materials.mat9} />
    </group>
  )
}

useGLTF.preload('/models/Plants - Assorted shelf plants.glb')
