/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 public/models/Tablet.glb -o src/components/Tablet.jsx -r public
*/

import { useGLTF } from "@react-three/drei";
import React from "react";
import { PlantInfo } from "./PlantInfo";

export function Tablet({ visible = true, ...props }) {
  const { nodes, materials } = useGLTF("/models/Tablet.glb");
  return (
    <group {...props} visible={visible} position-x={-1.5} dispose={null}>
      <PlantInfo visible={visible} position-x={-0.055} position-y={0.22} {...props} />
      <group rotation={[Math.PI / 2, 0, 0]} scale={0.0382}>
        <mesh
          geometry={nodes.ChamferBox003.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          geometry={nodes.ChamferCyl001.geometry}
          material={materials["03___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox001_1.geometry}
          material={materials["02___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox001_1_1.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox001_1_2.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox002_1.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox002_1_1.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox004_1.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox004_1_1.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox005_1.geometry}
          material={materials["01___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox005_1_1.geometry}
          material={materials["04___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox006_1.geometry}
          material={materials["03___Default"]}
        />
        <mesh
          geometry={nodes.ChamferBox006_1_1.geometry}
          material={materials["04___Default"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/Tablet.glb");
