/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant1.glb -o src/app/components/Plant1.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant1(props) {
  const { nodes, materials } = useGLTF('/models/plant1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plant_Yucca.geometry} material={materials['10461_Yucca_Plant_v1']} />
    </group>
  )
}

useGLTF.preload('/models/plant1.glb')
