/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -o src/app/components/Plant2.jsx -r public public/models/plant2.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant2(props) {
  const { nodes, materials } = useGLTF('/models/plant2.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -44.225, 0]} rotation={[Math.PI / 2, 0, 0]} scale={88.032}>
        <mesh geometry={nodes.awa_outdoor.geometry} material={materials['Material.002']} />
        <mesh geometry={nodes.awa_outdoor_1.geometry} material={materials.eb_house_plant_01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant2.glb')
