/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant2.glb -o src/app/components/Plant2.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant2(props) {
  const { nodes, materials } = useGLTF('/models/plant2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface8.geometry} material={materials.eb_house_plant_01} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/plant2.glb')
