/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -o src/app/components/Plant5.jsx -r public public/models/plant5.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant5(props) {
  const { nodes, materials } = useGLTF('/models/plant5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[0, -9.944, 0]} rotation={[Math.PI / 2, 0, 0]} scale={19.867}>
        <mesh geometry={nodes.awa_outdoor003.geometry} material={materials['Material.010']} />
        <mesh geometry={nodes.awa_outdoor003_1.geometry} material={materials['Material.008']} />
        <mesh geometry={nodes.awa_outdoor003_2.geometry} material={materials['1Newplan_2Petal1']} />
        <mesh geometry={nodes.awa_outdoor003_3.geometry} material={materials['1Newplan_Root']} />
        <mesh geometry={nodes.awa_outdoor003_4.geometry} material={materials['1Newplan_2Sepal']} />
        <mesh geometry={nodes.awa_outdoor003_5.geometry} material={materials['1Newplan_1Pdncle']} />
        <mesh geometry={nodes.awa_outdoor003_6.geometry} material={materials['1Newplan_Intrnd']} />
        <mesh geometry={nodes.awa_outdoor003_7.geometry} material={materials['1Newplan_1Bud']} />
        <mesh geometry={nodes.awa_outdoor003_8.geometry} material={materials['1Newplan_2Pdncle']} />
        <mesh geometry={nodes.awa_outdoor003_9.geometry} material={materials['1Newplan_1Pdcel']} />
        <mesh geometry={nodes.awa_outdoor003_10.geometry} material={materials['1Newplan_Leaf']} />
        <mesh geometry={nodes.awa_outdoor003_11.geometry} material={materials['1Newplan_2Flmnt']} />
        <mesh geometry={nodes.awa_outdoor003_12.geometry} material={materials['1Newplan_Petiole']} />
        <mesh geometry={nodes.awa_outdoor003_13.geometry} material={materials['1Newplan_Mrstm']} />
        <mesh geometry={nodes.awa_outdoor003_14.geometry} material={materials['1Newplan_1Bract']} />
        <mesh geometry={nodes.awa_outdoor003_15.geometry} material={materials['1Newplan_2Bud']} />
        <mesh geometry={nodes.awa_outdoor003_16.geometry} material={materials['1Newplan_FruitU']} />
        <mesh geometry={nodes.awa_outdoor003_17.geometry} material={materials['1Newplan_2Pdcel']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant5.glb')
