/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant4.glb -o src/app/components/Plant4.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Plant4(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/plant4.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <mesh name="Low-Poly_Plant_001" geometry={nodes['Low-Poly_Plant_001'].geometry} material={materials['Blatt.002']} />
        <mesh name="Low-Poly_Plant_" geometry={nodes['Low-Poly_Plant_'].geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant4.glb')
