/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant5.glb -o src/app/components/Plant5.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant5(props) {
  const { nodes, materials } = useGLTF('/models/plant5.glb')
  return (
    <group {...props} dispose={null}>
      <group position={[-1.18, 0, -1.513]} rotation={[Math.PI, 0, Math.PI]}>
        <mesh geometry={nodes.Circle_1.geometry} material={materials['Material.001']} />
        <mesh geometry={nodes.Circle_2.geometry} material={materials['1Newplan_2Petal1']} />
        <mesh geometry={nodes.Circle_3.geometry} material={materials['1Newplan_Root']} />
        <mesh geometry={nodes.Circle_4.geometry} material={materials['1Newplan_2Sepal']} />
        <mesh geometry={nodes.Circle_5.geometry} material={materials['1Newplan_1Pdncle']} />
        <mesh geometry={nodes.Circle_6.geometry} material={materials['1Newplan_Intrnd']} />
        <mesh geometry={nodes.Circle_7.geometry} material={materials['1Newplan_1Bud']} />
        <mesh geometry={nodes.Circle_8.geometry} material={materials['1Newplan_2Pdncle']} />
        <mesh geometry={nodes.Circle_9.geometry} material={materials['1Newplan_1Pdcel']} />
        <mesh geometry={nodes.Circle_10.geometry} material={materials['1Newplan_Leaf']} />
        <mesh geometry={nodes.Circle_11.geometry} material={materials['1Newplan_2Flmnt']} />
        <mesh geometry={nodes.Circle_12.geometry} material={materials['1Newplan_Petiole']} />
        <mesh geometry={nodes.Circle_13.geometry} material={materials['1Newplan_Mrstm']} />
        <mesh geometry={nodes.Circle_14.geometry} material={materials['1Newplan_1Bract']} />
        <mesh geometry={nodes.Circle_15.geometry} material={materials['1Newplan_2Bud']} />
        <mesh geometry={nodes.Circle_16.geometry} material={materials['1Newplan_FruitU']} />
        <mesh geometry={nodes.Circle_17.geometry} material={materials['1Newplan_2Pdcel']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant5.glb')
