/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 -o src/app/components/Plant3.jsx -r public public/models/plant3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant3(props) {
  const { nodes, materials } = useGLTF('/models/plant3.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Mesh002.geometry} material={materials['eb_house_plant_01.002']} />
        <mesh geometry={nodes.Mesh002_1.geometry} material={materials['Material.004']} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/plant3.glb')
