/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/plant3.glb -o src/app/components/Plant3.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Plant3(props) {
  const { nodes, materials } = useGLTF('/models/plant3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.polySurface7.geometry} material={materials['eb_house_plant_01.002']} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/plant3.glb')
