/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/room.glb -o src/app/components/Room.jsx -r public 
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Room(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/room.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Cube" scale={[5.741, 0.184, 5.741]}>
          <mesh name="Cube_1" geometry={nodes.Cube_1.geometry} material={materials.Material} />
          <mesh name="Cube_2" geometry={nodes.Cube_2.geometry} material={materials['Material.012']} />
          <mesh name="Cube_3" geometry={nodes.Cube_3.geometry} material={materials['Material.013']} />
          <mesh name="Cube_4" geometry={nodes.Cube_4.geometry} material={materials['Material.014']} />
        </group>
        <mesh name="Cube001" geometry={nodes.Cube001.geometry} material={materials['Material.008']} position={[-4.29, 2.482, -4.354]} scale={[0.094, 1.864, 0.094]}>
          <mesh name="plant" geometry={nodes.plant.geometry} material={materials['Material.003']} position={[0.076, -1.247, -0.098]} scale={[7.998, 0.404, 7.998]} />
        </mesh>
        <mesh name="window" geometry={nodes.window.geometry} material={materials['Material.018']} position={[-5.185, 3.719, 0.28]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.694, 1, 1.068]} />
        <mesh name="Cube002" geometry={nodes.Cube002.geometry} material={materials['Material.017']} position={[-4.97, 5.169, 0.273]} scale={[0.123, 0.123, 2.243]} />
        <mesh name="curtain" geometry={nodes.curtain.geometry} material={materials['Material.015']} position={[-4.878, 3.875, 0.321]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.788, 1, 1.199]} />
        <mesh name="curtain001" geometry={nodes.curtain001.geometry} material={materials['Material.015']} position={[-4.846, 3.875, -1.725]} rotation={[Math.PI / 2, 0, -Math.PI / 2]} scale={[1.788, 1, 1.199]} />
        <mesh name="sofa" geometry={nodes.sofa.geometry} material={materials['Material.001']} position={[0.332, 0.515, -3.724]} scale={[2.807, 1, 1.079]} />
        <mesh name="support" geometry={nodes.support.geometry} material={nodes.support.material} position={[2.636, 0.422, -4.343]} scale={0.215} />
        <mesh name="support001" geometry={nodes.support001.geometry} material={nodes.support001.material} position={[-2.002, 0.422, -4.343]} scale={0.215} />
        <mesh name="support002" geometry={nodes.support002.geometry} material={nodes.support002.material} position={[2.636, 0.422, -3.089]} scale={0.215} />
        <mesh name="support003" geometry={nodes.support003.geometry} material={nodes.support003.material} position={[-2.002, 0.422, -3.089]} scale={0.215} />
        <mesh name="sofa_2" geometry={nodes.sofa_2.geometry} material={nodes.sofa_2.material} position={[-3.581, 0.422, 2.249]} rotation={[-Math.PI, 1.391, -Math.PI]} scale={0.215}>
          <mesh name="sofa001" geometry={nodes.sofa001.geometry} material={materials['Material.001']} position={[10.871, 0.433, 2.883]} scale={[13.072, 4.657, 5.024]} />
          <mesh name="support004" geometry={nodes.support004.geometry} material={nodes.support004.material} position={[21.598, 0, 0]} />
          <mesh name="support006" geometry={nodes.support006.geometry} material={nodes.support006.material} position={[21.598, 0, 5.841]} />
          <mesh name="support007" geometry={nodes.support007.geometry} material={nodes.support007.material} position={[0, 0, 5.841]} />
        </mesh>
        <mesh name="rug" geometry={nodes.rug.geometry} material={materials['Material.011']} position={[0.804, 0.184, -0.016]} scale={[2.475, 1, 1.599]} />
        <mesh name="Cube003" geometry={nodes.Cube003.geometry} material={materials['Material.006']} position={[0.804, 1.581, -0.016]} scale={[2.097, 0.093, 1.23]} />
        <mesh name="cushion" geometry={nodes.cushion.geometry} material={materials['Material.003']} position={[-1.673, 1.577, -4.169]} scale={[0.385, 0.348, 0.129]} />
        <mesh name="cushion001" geometry={nodes.cushion001.geometry} material={materials['Material.003']} position={[1.864, 1.577, -4.169]} scale={[0.385, 0.348, 0.129]} />
        <mesh name="Cube004" geometry={nodes.Cube004.geometry} material={materials['Material.003']} position={[-3.454, 1.648, 1.474]} scale={[0.156, 0.51, 0.51]} />
        <mesh name="box" geometry={nodes.box.geometry} material={materials['Material.019']} position={[0.765, 1.92, -0.096]} rotation={[-Math.PI, 0, 0]} scale={[-0.452, -0.334, -0.438]} />
        <mesh name="paint" geometry={nodes.paint.geometry} material={materials['Material.009']} position={[-2.42, 4.514, -5.156]} scale={[1.199, 1.199, 0.149]} />
        <mesh name="Plane" geometry={nodes.Plane.geometry} material={materials['Material.011']} position={[0.24, -0.147, -0.104]} scale={20.315} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/room.glb')
